name: coffee-chat

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - chat-service
    networks:
      - rag-chat-network

  db:
    image: pgvector/pgvector:pg16
    container_name: ragchat-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db/volume:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - rag-chat-network

  user-service:
    image: ragchat/user-service:latest
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      JWT_REFRESH_EXPIRATION_MS: ${JWT_REFRESH_EXPIRATION_MS}
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - rag-chat-network

  chat-service:
    image: ragchat/chat-service:latest
    container_name: chat-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      CHAT_DB_SCHEMA: ${CHAT_DB_SCHEMA}
      USER_SERVICE_URL: http://user-service:8081/user
      JWT_SECRET: ${JWT_SECRET}
      RATE_LIMIT_CAPACITY: ${RATE_LIMIT_CAPACITY}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_HOST: ${OLLAMA_HOST}
    ports:
      - "8082:8082"
    depends_on:
      - db
      - user-service
    networks:
      - rag-chat-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - rag-chat-network

  llm:
   image: ollama/ollama:latest
   container_name: llm
   ports:
     - "11435:11434"
   volumes:
     - ./docker/llm/models:/root/.ollama
   environment:
     OLLAMA_MODELS: ${OLLAMA_MODEL}
   networks:
     - rag-chat-network
   restart: unless-stopped

networks:
  rag-chat-network:
    driver: bridge
