server:
  port: 8082
  servlet:
    context-path: /chat
  tomcat:
    connection-timeout: 60000

spring:
  application:
    name: chat-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${CHAT_DB_SCHEMA:chat_service}
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ${CHAT_DB_SCHEMA:chat_service}
    baseline-on-migrate: true
  ai:
    ollama:
      base-url: ${OLLAMA_HOST}
      chat:
        options:
          model: ${OLLAMA_MODEL}
    vectorstore:
      pgvector:
        initialize-schema: true
        schema-name: ${CHAT_DB_SCHEMA:chat_service}
        dimensions: 768
        distance-type: COSINE_DISTANCE

user-service:
  url: ${USER_SERVICE_URL:http://user-service:8081/user}

jwt:
  secret: ${JWT_SECRET}

rate-limit:
  capacity: ${RATE_LIMIT_CAPACITY:100}
  refill-tokens: ${RATE_LIMIT_REFILL_TOKENS:100}
  refill-duration-minutes: ${RATE_LIMIT_REFILL_DURATION:1}
